{% set name = "atpublic" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 466ef10d0c8bbd14fd02a5fbd5a8b6af6a846373d91106d3a07c16d72d96b63e


build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python

test:
  imports:
    - public
    - public.public
    - public.private
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://gitlab.com/warsaw/public
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: |
    A very simple decorator and function which populates a module's __all__ and optionally
    the module globals.
  description: |
    This library provides two very simple decorators that document the publicness of the names in your module.
    They keep your module's __all__ in sync so you don't have to.
  doc_url: https://public.readthedocs.io
  dev_url: https://gitlab.com/warsaw/public

extra:
  recipe-maintainers:
    - johanneskoester
    - cpcloud
