{% set name = "atpublic" %}
{% set version = "2.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d6b9167fc3e09a2de2d2adcfc9a1b48d84eab70753c97de3800362e1703e3367


build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - atpublic
    - atpublic.tests

about:
  home: http://public.readthedocs.io/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: |
    A very simple decorator and function which populates a module’s __all__ and optionally 
    the module globals.
  doc_url: https://public.readthedocs.io

extra:
  recipe-maintainers:
    - johanneskoester
    - cpcloud
