travis:
  secure:
    BINSTAR_TOKEN: U2vfCXlkfGciOxPl/hnm5BWsTwhYNghVz4+M2lPXC4fnkzJLwdOaHwHnrf9v8yE5zAM5fPWHompd14uAuBcQhGDVG1NmvhCHzLyJn69QteHjgDPc3mjcfLYjKw8HIOVCZCgqKUVf+rkUj2y6yTP/0/jRnuvjs0Q631e1/5WipjQogNdk0x3Fvhg6eDfviw4p3G1KSufGZ+vUYkttK4qVRPmwojvbQsy9QJOs8mwRPtBQtF0c6VM0aKFghv7TR7B4oBm3sCA3lHLuVarOCs7qHcgNmqzjd8F570RbhL5AOYHlBZkzicJh3afjYI/KeSSXT2zl+AycXCaVd+F/BQoj2JaRPFGi1o7nb0510mi1xPfB+lcQOpHvqxMPFun7C99IED7yUcLJ4FL95s26F0iSNGo1cETN6QAOjzI3YydgnrnGqiyHO8HFK+ieQVxDPRFQF4prhpTxRpEFXiruQ3MNOLwDroKWyEM2HXEeKrfcUrGNj1ImbhUhazYfCP2ObGRPiNSMphEUFv8njjA83cSSL4j/f640MXSrCIQuSX+ct60R/ETk/AzzsNlpCQ4aYLxNY5dAq4FYQqjSoPye8C9tJ/cF855xhSZhv0mbcWYe3c4U57SBgCpkXm1FBsgmJtp29Qaa/PS78Gw9am7/ml/31yUwf8TyiDB247UmSMqH0R0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
